### ISSUE TITLE
Issue with the readme

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/css-selectors#11]
@gj 

in the `child` part of the readme, a student tested out the example code while reading along. There was an issue with the html part of the example.

css: 
```
#list > li {
  color: black;
}
```

html:

```
<ul id="list">
  <li>child</li>
  <li>child
    <ul>
      <li>grand child</li>
    </ul>
  </li>
</ul>
```

she made the color red to see the changes and noticed the grandchild would change as well. However i noticed that in the html section, the grand child is part of the child's li.

```
<li>child
    <ul>
      <li>grand child</li>
    </ul>
  </li>
```

so i had her switch it to

```
<li>child</li>
<ul>
  <li>grand child</li>
</ul>
```

i thought it might also be a good idea to change it in the read me also in case any other students are following along.

**Comment by gj** [comment]
Hi @Enoch2k2 !

The lesson is correct as-is — the student's misunderstanding stems from the fact that `color` is an inherited CSS property, so, even though `#list > li` only grabs the two top-level elements, the nested `<li>grand child</li>` will inherit the property of `color: red;`

To illustrate the point, here's a fiddle with an inherited property (`color`) and an un-inherited property (`border`): https://jsfiddle.net/gabej/f4a6ar1c/3/

**Comment by gj** [comment]
I updated the lesson to help students avoid this misunderstanding: https://github.com/learn-co-curriculum/css-selectors/commit/b2de186bc769a91c0fa6855f2bd6223950171cd3
